### ISSUE TITLE
oauth2client has no aatribute 'file'

### ISSUE THREAD

**Issue by Innie080** [johnwargo/Pi-Remind-Zero-Blinkt#2]
Not having much luck with this little project.
Running remind.py returns an error.

Line 153 in get_credentials
store=oauth2client.file.Storage(credential_path)
attributeError: module 'oauth2client' has no attribute 'file'

I read that oauth2 is deprecated is there a chance this script may be updated?

Sorry i am a hobbiest and not proficient in Python (although i tried)

**Comment by johnwargo** [comment]
I don't know, I haven't tested this project in years. When people have had problems like this before (with the other Pi Remind projects) it came down to the version of raspbian they installed. 

https://github.com/tokland/youtube-upload/issues/245 they mention changing the import statement to fix it.

**Comment by johnwargo** [comment]
Apparently someone posted a Pull Request to implement the same fix in https://github.com/johnwargo/pi-remind-zero-blinkt/pull/1. So it must work. I'll merge it, you can try it again.

**Comment by Innie080** [comment]
Hi John,

Your merge has indeed fixed the Script. I have successfully registered the token and have pi-remind running. Thanks

**Comment by Innie080** [comment]
Hi, the instruction to install the Blinkt library has changed slightly from your github instruction it is now....
 curl https://get.pimoroni.com/blinkt | bash

**Comment by johnwargo** [comment]
updated, thanks
